import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ThemeProvider } from "@/components/theme-provider"
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "tech innovant",
  description: "Generated by tech innovant",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  
  return (
  <html lang="en">
  <body className={inter.className}>
  
        <main className="relative overflow-hidden">
          <Navbar  />
          {children}
          <Footer  />
        </main>
     
  </body>
  </html>
  );
}
